### ISSUE TITLE
Flow based typing doesn't narrow callable arguments in else block correctly

### ISSUE THREAD

**Issue by sadmac7000** [ceylon/ceylon-spec#1203]
This:
```ceylon
void testFunc<FuncType>(Boolean(FuncType) func)
        given FuncType of String | Integer {
    if (is Boolean(String) func) {
        func("hi");
    } else {
        func(6);
    }
}
```

Yields this:
```
source/test/testme.ceylon:6: error: argument must be assignable to parameter type: 'Integer' is not assignable to 'FuncType'
        func(6);
            ^
1 error
```

**Comment by gavinking** [comment]
Casey is this with the very latest typechecker from git? Because I did some work in this area last week.

**Comment by sadmac7000** [comment]
Yup. Just pulled again to confirm.

**Comment by gavinking** [comment]
OK, so after looking more carefully I realized that this is actually normal.

According to §3.4.1, there is no rule which says:

- `X|Y` covers `Z` => `Cov<X|Y>` covers `Cov<Z>`. The reason for that is reified generics. An instance of `Cov<Z>` is actually not an instance of `Cov<X|Y>` at runtime because of the reified type argument. This is a bit subtle!

Now, in this _particular case_, such a rule _would_ be sound, because `X` is a type parameter `FuncType`, and so at runtime it has to be either `String`, `Integer`, or `String|Integer`. But I don't think I would want to complicate the coverage analysis just for this case.

I'm going to close this, just because I don't think it's worth fixing right now.

**Comment by RossTate** [comment]
Hmm, I might be able to apply material-shape separation so that covering can be fully integrated with subtyping and still be decidable. We're working on something related, and I think I could work this in.

**Comment by gavinking** [comment]
@RossTate coverage is integated with subtyping but this is a special case of something which in general would not be sound because of reified generics.

**Comment by RossTate** [comment]
If coverage is integrated into subtyping then:
`X|Y` covers `Z` => `Z` subtype of `X|Y` => `Cov<Z>` subtype of `Cov<X|Y>` => `Cov<X|Y>` covers `Cov<Z>`

**Comment by gavinking** [comment]
> `X|Y` covers `Z` => `Z` subtype of `X|Y`

Nope. Coverage is a weaker relationship than subtyping.   `Z` subtype of `X|Y` => `X|Y` covers `Z` but not the converse.

**Comment by RossTate** [comment]
So coverage isn't integrated into subtyping then, in which case my earlier statement still points out a potential contribution.

**Comment by gavinking** [comment]
What does "integrated" mean here? If it means "exactly the same", then no, it's not. If it means "is aware of", then yes, it is.

**Comment by RossTate** [comment]
Coverage would imply subtyping. I'm curious, how is subtyping currently "aware of" coverage?

**Comment by gavinking** [comment]
Coverage is aware of subtyping, not the other way.

**Comment by RossTate** [comment]
Ah, so I'm saying we might be able to make the other way possible without screwing up decidability, by using the material-shape separation.

**Comment by gavinking** [comment]
OK, that would be perfect, a big improvement.
