### ISSUE TITLE
Replace `boolean` fields on the model with `int` bitfields

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1204]
That should save a lot of space because we can pack 32 booleans in an `int` where a `boolean` field takes about as much space as a `byte` (8 bits). That should be straightforward and not result in any change to the clients and the public API, but it needs validation with a profiler first.

**Comment by gavinking** [comment]
@FroMage is this really truly for 1.2?

**Comment by FroMage** [comment]
Well, only if we have time for that. Otherwise we can move it.

**Comment by NiematojakTomasz** [comment]
I just want to mention here that JVM is not obligated to store boolean in byte and is free to perform such optimization itself. See http://docs.oracle.com/javase/tutorial/java/nutsandbolts/datatypes.html

However, it probably wouldn't affect bytecode compatibility neither.

**Comment by gavinking** [comment]
So I tried squeezing a bunch of the `boolean` model fields into `int`s and it does not seem to have had any noticeable impact on the IDE build (which we believe to be memory-bound).

There are also some `boolean`s in the `LazyXxxx` classes, so I suppose it's possible we would notice something positive if we also did it for them. But I'm pretty skeptical.

@FroMage, please feel free to improve it / revert it as you prefer.

I'm closing this issue because it doesn't belong here (it belongs in `ceylon-model`) and because it doesn't seem like it's worth spending much more time on this right now.
