### ISSUE TITLE
late attributes in method

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#1218]
I've come across a need for late attributes in methods but it's not allowed. Is there any reason?

**Comment by gavinking** [comment]
Well the reason for `late` is to let you set something after the completion of the scope in which it is declared. Since a local is not usually accessible afterwards, that seemed useful.

Now, the only case where it could be accessible if it is captured by a local function, in which case I suppose `late` could make sense...

**Comment by FroMage** [comment]
I had the following test to write:

```
late Exception x;
try{
 foo();
 assert(false);
}catch(Exception x1){
 x = x1;
}
try{
 foo();
 assert(false);
}catch(Exception x2){
 assert(x == x2);
}
```

**Comment by gavinking** [comment]
You're totally not selling me. You want to `assert` that something is equal to something that might not have been set? Yeeeeeeew.

**Comment by FroMage** [comment]
Well, it must have been set and if not I want code to break. The problem is that working around this requires me to set `x` as `variable` _and_ optional _and_ assert that it's not null :(

**Comment by gavinking** [comment]
Well then what we should do is improve definite assignment analysis. Not hack shit.

**Comment by FroMage** [comment]
By all means ;)

**Comment by gavinking** [comment]
So submit an issue requesting that and close this one :)
