### ISSUE TITLE
unable to inspect annotations on non top-level anonymous class

### ISSUE THREAD

**Issue by LisiLisenok** [ceylon/ceylon-spec#1232]
unable to find annotations If object extends some class and passed to some function in order to inspect annotations. Neither annotations nor objectValue are defined on nested object.
For class instancies or top-level object it works well. But if object is defined inside a function, no any annotation found.

See example below and also discussion thread https://groups.google.com/forum/#!topic/ceylon-users/9DDddMATslY
```ceylon
// some base class
abstract class BaseClass() {}

see( `class BaseClass` ) // class - annotation exists
class SomeClass() {}

see( `class SomeClass` ) // top-level object - annotation exists
object someObject extends SomeClass() {}

// main function
shared void testAnnotation() {
	
	see( `value someObject` ) // internal object - annotation exists
	object internalObject extends SomeClass() {}
	
	printAnnotations( SomeClass() ); // class instance - Ok
	printAnnotations( someObject ); // top-level object - Ok
	printAnnotations( internalObject ); // internal object - no any annotation found
	
}

void printAnnotations( SomeClass obj )
{
	assert( is Class classType = type( obj ) );
	print( "\n" );
	print( classType );
	if ( exists anonymClass = classType.declaration.objectValue ) {
		for( annotation in anonymClass.annotations<SeeAnnotation>() ) {
			print( annotation );
		}
	}
	else {
		for( annotation in classType.declaration.annotations<SeeAnnotation>() ) {
			print( annotation );
		}
	}
}
```

**Comment by gavinking** [comment]
Note that there are several problems mixed together in this bug report:

- The spec needs to clarify that annotations of anonymous classes apply to the `ValueDeclaration`, not the `ClassDeclaration`.
- The JVM backend needs to be modified to actually implement that semantic, and not return `SeeAnnotation`s of anonymous classes when the class itself is queried.
- The JS backend needs to be fixed so that this code actually runs and doesn't blow up.

**Comment by gavinking** [comment]
Ah wait, I misunderstood the code. Actually the JVM backend is doing fine. The only potential issue is that for a local `object` declaration, `` `class foo`.objectValue `` evaluates to `null`.

**Comment by LisiLisenok** [comment]
agree) if objectValue evaluates to actual local object it can help. In any case I know nothing about JVM backend and don't know how I can help.
Another solution might be to restrict annotations on objects.

**Comment by tombentley** [comment]
>  The only potential issue is that for a local `object` declaration, `` `class foo`.objectValue `` evaluates to `null`.

@gavinking well what else do you propose it should do? It's a local declaration after all. I suppose we just need to fix the documentation of `objectValue` to say it can return null in the case of a local anonymous class?

**Comment by FroMage** [comment]
If we're using `class foo` it means the local class is in scope, so must its value be, no?

**Comment by tombentley** [comment]
@FroMage well I thought we didn't support local values:

    void m(){
        value s = "";
        value sd = `value s`;// metamodel reference to local declaration
    }

**Comment by FroMage** [comment]
Well, TBH we do support local types. Perhaps not as metamodel literals though. I _think_ we could only support `objectValue` for local type metamodel literals. Not when they come from somewhere else in the metamodel as that has no access to scope. Shame though.

**Comment by gavinking** [comment]
What is the history behind `ClassDeclaration.objectValue`? It seems to quite badly named (it's an `ValueDeclaration`, not a `Value`), and also not very typesafe. I feel like it would be better if it were declared on a separate interface called `AnonymousClassDeclaration`, and named `valueDeclaration`.

In this case, simply returning `null` doesn't seem like the correct behavior.

**Comment by FroMage** [comment]
https://github.com/ceylon/ceylon.language/issues/433#issuecomment-42662194 HAHAHAHAHA ;)

**Comment by tombentley** [comment]
Should we add the `AnonymousClassDeclaration` interface then? (Because I really want to close ceylon/ceylon-compiler#2081)

**Comment by gavinking** [comment]
@tombentley I suppose, if you like.

**Comment by gavinking** [comment]
OK, so there has been some good progress on this stuff. Now the remaining inconsistencies are:

1. On JS I can get a `ValueDeclaration` of `ClassDeclaration` for a local `object`. On JVM I can only get the `ClassDeclaration`. I can never get the `ValueDeclaration`.
2. On the JVM I can get the `SeeAnnotation`s for an `object` by inspecting its `ValueDeclaration`. On JS I cannot.

@FroMage @chochos Your feedback on those issues. Should I open new issues for either of them? Because I'm inclined to close this issue, since there is no problem in the typechecker.

**Comment by gavinking** [comment]
I have opened https://github.com/ceylon/ceylon.language/issues/661.

@FroMage let me know if you think I should open an issue about the null `ValueDeclaration`.

Closing.

**Comment by chochos** [comment]
Wait, I don't understand... first you say on JVM you can never get the `ValueDeclaration`, and then you say you can get the `see` annotation for an object by inspecting its `ValueDeclaration`.

I remember there was an issue for the first item (getting value or class declaration for an object), that's why you can get both on JS...

**Comment by gavinking** [comment]
There are two cases here: a top level object, and a local object. They are different.

**Comment by FroMage** [comment]
Well, should we be able to get the value or not? ATM the test fails because we can't, for local values on the JVM.

**Comment by gavinking** [comment]
@FroMage well you tell me. Can you implement it?

**Comment by FroMage** [comment]
Let's try to think about this rationally:

- We can get the type declaration for local objets, since we _have_ to for its instances,
- that type declaration is the same for every invocation of the container of the local declaration,
- the instance value of the object differs for every invocation of the container: it is not constant,
- therefore, we can't obtain it from its type declaration.

Sure, I can make it work, by recording the first value, provided you don't access its type before we set its value, but that'd just be wrong in every subsequent invocation. IMO we should not support this.

**Comment by gavinking** [comment]
Sounds right to me. So then JS needs to do the same since the same reasoning applies. Currently it does something different.

**Comment by chochos** [comment]
So... `objectValue` should return `null` on local anonymous classes? Or should it throw? I've fixed the annotation issue for member objects BTW.

**Comment by FroMage** [comment]
Well, `objectValue` can be null, so why not make it so, and fix the doc to explain.

**Comment by gavinking** [comment]
Null sounds better to me :)

**Comment by gavinking** [comment]
Heh what is `class null`.objectValue? :)

**Comment by FroMage** [comment]
A `ValueDeclaration`, why? ;)

**Comment by gavinking** [comment]
Ah OK :)
