### ISSUE TITLE
Permit metamodel refs to class/interface members of anonymous classes

### ISSUE THREAD

**Issue by tombentley** [ceylon/ceylon-spec#1243]
As mentioned [here](https://github.com/ceylon/ceylon-compiler/issues/1998#issuecomment-77148384) we should allow this:

```ceylon
object toplevel {
    shared class Member() {}
}
void run() {
    value z=  `toplevel.Member`;//syntex error expecting initialial lower-case identifier
}
```

**Comment by gavinking** [comment]
Hrm, I bet this works:

```ceylon
value z=  `\Itoplevel.Member`;
```

**Comment by tombentley** [comment]
Well yes, it does (though it's ugly enough that I want to stab out my own eyes). It's also inconsistent wrt attributes and methods when the `object` is a member of a class:

```ceylon
class MemberObjectContainer(){
    shared object memberObject {
        shared Integer attribute = 2;
        shared Integer method() => 2;
        shared class Klass() {}
    }
    shared void test(MemberObjectContainer other){
        Attribute<MemberObjectContainer,Integer,Nothing> v = `memberObject.attribute`;
        Method<MemberObjectContainer,Integer,[]> f = `memberObject.method`;
        MemberClass<MemberObjectContainer.\ImemberObject,MemberObjectContainer.\ImemberObject.Klass,[]> c = `\ImemberObject.Klass`;
    }
}
```

The container of the `Attribute` and `Method` is `MemberObjectContainer`, but the `MemberClass`'s container type is `MemberObjectContainer.\ImemberObject`.

**Comment by gavinking** [comment]
OK, @tombentley, you asked for it!

Now you're going to have to fix up some backend problems, like, for example, this one:

```ceylon
object x { shared object y {} }

value xy = `x.y`;
```

FTR, that code blows up the backend.

**Comment by tombentley** [comment]
@gavinking I don't get why the type of `` `memberObject.Klass` `` is `MemberClass<\ImemberObject,\ImemberObject.Klass,[]>` so I have to bind to the anonymous class instance `other.memberObject` when for the `Method` and `Attribute` cases their container is `ClassContainer` so I have to bind to `other`. Is this inconsistency intentional?

**Comment by gavinking** [comment]
@tombentley Fixed. That's assuming we still want to keep that "feature".

**Comment by tombentley** [comment]
We now have 

    MemberClass<ClassContainer,\ImemberObject.Klass,[]> c = `memberObject.Klass`
    c(other);//to bind

But I can still say

    assert(is MemberClass<ClassContainer.\ImemberObject,\ImemberObject.Klass,[]> xx=typeLiteral<\ImemberObject.Klass>());
    xx(other.memberObject);//to bind

I find it a bit weird that we can have two different instantiations of `MemberClass` which refer to the same thing! It means at runtime I have to figure out whether I need to go looking up the `object`(s) from the instances being bound to, or not.

**Comment by tombentley** [comment]
@gavinking, I'm now convinced that I don't want to keep this "feature". In particular is seems that 

    `memberObject.attribute`

only works because the code generator can do stuff under the covers that it shouldn't (in particular it can pass reified type arguments which don't match what they should be). What would be the equivalent Ceylon

        assert(is MemberClass<Container,\ImemberObject,Nothing> mo = typeLiteral<\ImemberObject>());
        assert(exists a2 = mo.getAttribute<Container,Integer>("attribute"));

fails at runtime on the second assert because `getAttribute()` returns null for the `TypeDescriptor being passed (the one for `Container`). To get something that works we need to pass it the `TypeDescriptor` for `memberObject`,

        assert(exists a = mo.getAttribute<Container.\ImemberObject,Integer>("attribute"));
        a(other.memberObject);

 but that necessarily means being honest about what the container type is and not pretend it's the first denoteable outer class.

**Comment by gavinking** [comment]
@tombentley I'm inclined to agree. I'm happy to remove this hack, frankly. We don't need it anymore.

**Comment by gavinking** [comment]
@tombentley OK, after spending a couple of days on this, I've come to two realizations:

1. I hate you.
2. I think we should roll this back, and require that anonymous class types be expressed using the `\Iname` syntax.

I guess I should have seen this more clearly earlier by taking a proper step back and thinking it through from basics, instead of trying to do it by piling fixes for fixes on top of each other, but at least now I _do_ see it clearly.

The thing is that to do this in a non-broken way, you would have to completely duplicate the whole type expression grammar in both the spec and the ANTLR grammar, with the two duplicate versions differing only in that one permits initial lowercase types and one doesn't.

Otherwise, you have to explain to people why `String[]`, `Boolean|Null`, and `process` all work, but `process[]` and `true|false` don't. I think that's going to be a quite difficult task. So I think we should essentially roll back to where we were before.

The one caveat is that I guess we should continue to support stuff like `function process.writeLine`, if only  for reasons of backwards compatibility with 1.1.

**Comment by gavinking** [comment]
OK, so the resolution here was to roll back most of this work and:

1. Support things like `class foo.bar.baz` and `function Foo.bar.fun` in _reference expressions_.
2. Remove the hacked-in support for `foo.fun` in _metamodel expressions_, requiring you to write `\Ifoo.fun`, thus resolving the irregularity spotted by @tombentley. Note that this is a (very, _very_ minor) backwards-incompatible change to the language syntax!

**Comment by gavinking** [comment]
Original issue for future reference: #712.
