### ISSUE TITLE
constructors and return

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1288]
Here's an interesting case:

```ceylon
    class Foo {
        shared new () {
            return;
        }
        shared new Baz() {}
        print("done");
    }
```

Currently this results in an `unreachable statement` error on the `print()` statement.

I'm not sure that this is precisely _wrong_, but it's not obviously the only thing that could be correct.

So I need to think it through a little further and probably clarify this in the spec.

**Comment by jvasileff** [comment]
Since constructor chaining doesn't work like method calls, I find `return` within constructors (or anywhere else prior to the end of the last constructor) pretty confusing. I can't really guess at the correct behavior for:

```ceylon
shared
void initializationReturn() {
    class Foo {
        shared new Bar() {
            return;
        }
        print("unreachable?");
        shared new Baz() extends Bar() {
            print("unreachable too?");            
        }
        print("unreachable three?");
    }
    Foo.Baz();
    // Prints:
    //    unreachable?
    //    unreachable too?
    //    unreachable three?
}
```

unless `extends Bar()` were made illegal by considering `Baz()` unreachable as soon as `extends Bar()` is added.

**Comment by gavinking** [comment]
FTR, I doubt there is any especially "correct" behavior&mdash;we just need to pick something not too broken.

However, it's clear from the example you just gave that _something_ is broken here. I can't imagine why your example is accepted by the typechecker, and mine is not. That's wrong.

**Comment by luolong** [comment]
Well, if I'd have to pick, then to me the most intuitive approach is if `return` in a constructor would only return from that specific constructor. End of story.

E.g.:
```ceylon
shared
void initializationReturn() {
    class Foo {
        print("1")
        shared new Bar() {
            print("1.5")
            return;
            print("unreachable!");
        }
        print("2");
        shared new Baz() extends Bar() {
            print("2.5");            
        }
        print("3");
    }
    Foo.Baz();
    // Prints:
    //    1
    //    1.5
    //    2
    //    2.5
    //    3 
}
```

**Comment by gavinking** [comment]
Oh, wait, this error is a backend error. So actually the typechecker is indeed interpreting `return` the way that @jvasileff argues is the only correct way, but then the backend can't deal with that.

@tombentley @chochos WDYT? Is this something you can easily handle, or should I simply outlaw `return` in a constructor which doesn't occur at the end of the initializer?

**Comment by gavinking** [comment]
For now, I have simply disallowed `throw` and `return` in constructors. If @tombentley thinks he can implement support for the code above, I can easily remove this check.

I tried to detect initializer statements after a `return`ing constructor, but that turned out to be really way more complex that I was expecting.

**Comment by tombentley** [comment]
@gavinking I'm not quite sure what the indented interpretation of is. Are we saying that `return` simply returns from that constructor, and all following initializer statements should be executed?

**Comment by gavinking** [comment]
> Are we saying that `return` simply returns from that constructor, and all following initializer statements should be executed?

Yes, I think that's the best interpretation.

**Comment by jvasileff** [comment]
FTR, my thought was that `return` should return all the way back to the original caller, outside the class. This would mean that most of my example would be flagged illegal, which I tend to think is a good thing since `return` is confusing in the context of constructors & extends.

The sample output I included was what it was doing, not what I suggested it should do.

I think @luolong's example is reasonable too, but it's also more like a "goto end of block" than a return to a caller. So, I think its behavior is less clear/obvious than if everything after a return were simply disallowed.

**Comment by gavinking** [comment]
Right, there are two sorta-reasonable interpretations, depending upon whether you think a constructor is more like a control flow structure inside the initializer, or a whole separate function by itself. I _think_ that in practice it will be more useful to only return to the end of the constructor, and let the rest of the initializer be executed.

**Comment by gavinking** [comment]
OTOH, `throw` and `assert(false)` are slightly different. They really do immediately exit the whole initializer.

**Comment by jvasileff** [comment]
Well, a third variation that no one is proposing and may not even be possible to implement is that my example would print:
```
Foo.Baz();
    // Prints:
    //    unreachable too?
    //    unreachable three?
```
But I think *readers* of code could easily believe that to be the expected output.

**Comment by gavinking** [comment]
@jvasileff hah, crazy. No, I don't think that's what we want...

**Comment by chochos** [comment]
so what's it gonna be? allow `return` in constructors, and it means just end the execution of that constructor but run the rest of the initializer?

**Comment by luolong** [comment]
I would vote for this interpretation, yes.

It is the most sensible way to interpret return statements given the syntax we have.
Anything else will strike me as as highly surprising behavior.

Constructor blocks are syntactically very similar to method or getter blocks, so returning from a constructor and exiting the entire initializer is somewhat unexpected.

Also, if you really need to exit the whole initializer section, you can have return inside the initializer section.

`throw` and `assert` are different, as they usually tend to work across multiple call stack frames anyway &mdash; `return` on the other hand usually works within a single call stack frame, which this syntax currently makes us believe.

OTOH, if we'd be free to change the constructor syntax so that it would more resemble conditional block, I would be okay with returning from the entire intializer block.

Something like that maybe:
```ceylon
    class Foo {
        if (shared new Bar()) {
            return;
        }
        print("unreachable?");
        if (shared new Baz() extends Bar()) {
            print("unreachable too?");            
        }
        print("unreachable three?");
    }
```

or this
```ceylon
    class Foo {
        shared case (new Bar()) {
            return;
        }
        print("unreachable?");
        shared case (new Baz() extends Bar()) {
            print("unreachable too?");            
        }
        print("unreachable three?");
    }
```

**Comment by gavinking** [comment]
Yes.

**Comment by gavinking** [comment]
> so what's it gonna be? allow `return` in constructors, and it means just end the execution of that constructor but run the rest of the initializer?

Yes, that. End execution of _the current_ constructor and resume the initializer or delegating constructor.

**Comment by tombentley** [comment]
OK, thanks. I'll try to fix this one today. If I dare pull @FroMage's world of hurt, that is.

**Comment by chochos** [comment]
Is this is some branch?

**Comment by tombentley** [comment]
No, just comment out the errors in the type checker

**Comment by tombentley** [comment]
I just implemented support for this in the JVM backend, and believe @chochos implemented it already in the JS backend, so I guess we just need some language module tests and the removal of the typechecker error.

**Comment by jvasileff** [comment]
@gavinking this should be for 1.2, right?

**Comment by chochos** [comment]
Are we including this in 1.2 or not?

**Comment by tombentley** [comment]
It should be as far as I'm concerned, a since I implemented it for the JVM compiler.

**Comment by gavinking** [comment]
Is it implemented in both backends yet?

**Comment by gavinking** [comment]
Answering my own question: yes, it seems to work perfectly on both backends. I can therefore close this issue.

**Comment by gavinking** [comment]
@tombentley is it _really_ still the case that you can't handle `throw` in a constructor? Because `assert(false)` seems to work, and they're basically the same thing....

Or was there some particular cases where `throw` didn't work?

**Comment by tombentley** [comment]
@gavinking I suppose there was never a problem with `throw`, since control would resume at the first applicable `catch` (or `finally`), and since a constructor definition cannot be enclosed in a try/catch, that means that control cannot be resumed in the initializer, so we're good. 

But it's not like I have tests for this.

**Comment by gavinking** [comment]
@tombentley yep, seems to be working, thanks.
