### ISSUE TITLE
Type inference does not work with function using multiple parameters lists

### ISSUE THREAD

**Issue by renatoathaydes** [ceylon/ceylon-spec#1292]
The following code does not compile:

```ceylon
shared Item theItem<Item>(String name)(Item item) => item;

void run() {
    value x = theItem("")(1); // ERROR on the 1
}
```

Because of error:

```
Argument must be assignable to parameter type: Integer is not assignable to Nothing
```

Explicitly giving the type to the function fixes the problem.

```ceylon
value x = theItem<Integer>("")(1); // OK
```

However, this should work because when the function has only one parameter list, the explicit type declaration is not required:

```ceylon
shared Item theItem<Item>(Item item) => item;

void run() {
    value x = theItem(1); // OK!
}
```

**Comment by RossTate** [comment]
Looking at #673, it seems y'all decided type-argument inference wasn't to blame here, but rather you need to support another invocation pattern. If so, y'all should change the name of the issue. If not, I'll pipe in about type-argument inference.

**Comment by renatoathaydes** [comment]
From the user's point of view, I'd say the problem is just not being able to infer types and having to declare them explicitly in parameter lists which are not the first one. So in my opinion the issue description is accurate even if the root cause is something else.

**Comment by gavinking** [comment]
The issue description is basically correct. Type argument inference isn't _meant_ to take into account any but the first argument list, at least not according to the spec. Now, perhaps it wouldn't be crazy to add that functionality, but it's kinda contrary to the reasons why you typically have multiple parameter lists. Either:

1. you expect to directly invoke the first list, and then pass the result around before indirectly invoking the second list, or
2. you want to use the first parameter list to infer the type parameters, and use the result of that inference to typecheck the second parameter list, and infer the types of its anonymous function arguments.

Consider `Iterable.fold()()`. We can write:

```ceylon
values.fold(0.0)((s,x)=>s+x)
```

Precisely *because* the second argument list doesn't enter into the process of inferring type arguments, and so therefore we can subsequently use those inferred type arguments when assigning types to the parameters of the anonymous function.

Now, _perhaps_ there is a _way_ more complex algorithm that would let you get both, but this process is already _extremely_ complex and over-constrained (it's also constrained by having to deal with Java overloading), and it was _very_ hard to make this much work.

**Comment by gavinking** [comment]
I note, FWIW, that Scala has the same limitation. Quite likely for the same reason.

**Comment by jvasileff** [comment]
Coincidentally, I stumbled upon [this](http://pchiusano.blogspot.com/2011/05/making-most-of-scalas-extremely-limited.html) related discussion a week or so ago.

**Comment by renatoathaydes** [comment]
I can see the problem. At least when https://github.com/ceylon/ceylon-spec/issues/810 gets fixed, this limitation will become less apparent. @gavinking Feel free to close this issue if you think it's appropriate.

**Comment by gavinking** [comment]
OK, closing.
