### ISSUE TITLE
allow object declarations and value constructors to have an initial uppercase name

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#1345]
After some reflection, it seems to me that the language would be more regular and easier to use if `object` declarations, and the new value constructors proposed in #1129 were allowed to have initial-uppercase names, and the previous tradition of giving them initial-lowercase names were deprecated or otherwise discouraged.

The reasoning behind this change is:

1. Writing `\Itrue` drives us nuts.
2. It makes much clearer the relationship that an `object` is just a `class` with no parameters, and that a value constructor is just a constructor with no parameters. We don't have a case-difference between `value`s and `function`s, which bear the same relationship to each other.
3. It will probably be easier to explain these concepts in the spec.
4. It can be done without breaking backward compatibility.

Argument against the change include:

1. It makes it harder to visually distinguish something that is "just a single value".
2. We prefer to write `true` and `false`, not `True` and `False`, so we would have both defined in the language module, i.e. `shared Boolean true => True; shared Boolean false => False;`
3. It's a deckchair-moving change that just makes the language appear less stable without introducing any additional expressiveness.

Some of these objections would be alleviated by just blessing the use of both forms, and leaving it up to the developer to decide whether they want an easily-denotable type or not.

**Comment by gavinking** [comment]
This is now implemented in the `1345` branch, so you guys can try it out.

**Comment by lucaswerkmeister** [comment]
Argument against: `X.y` is now visually ambiguous between a static expression and a member of a toplevel object.

In general, I think it’s weird that we would have a value with an uppercase name. But that’s just the inverse of “it’s weird that we have classes with a lowercase name”. I guess the uppercase value one bothers me more because I currently think of objects as values, not classes.

**Comment by gavinking** [comment]
> Argument against: `X.y` is now visually ambiguous between a static expression and a member of a toplevel object.

But ... I don't think those two notions are very different! They look like much the same thing to me: a direct reference to a member of a class. In the case that there are multiple instances of the class, you need to provide an instance. In the case that there is just one instance, you don't. Sounds intuitive to me.

**Comment by gavinking** [comment]
> In general, I think it’s weird that we would have a value with an uppercase name. ... I guess the uppercase value one bothers me more because I currently think of objects as values, not classes.

Yes. I'm definitely not used to the idea that `True` is a single value. I _suppose_ I will get used to it. It's always possible that I won't, however.

**Comment by lucaswerkmeister** [comment]
> But ... I don't think those two notions are very different!

Perhaps conceptually… but they’re used completely differently. One is a callable, typically used (in my experience) for `map`, `filter`, etc.. The other is a regular value, used for whatever you normally use values for.

OTOH, perhaps that means that the difference isn’t so bad after all, since a reader will usually be able to infer the meaning from the context.

**Comment by gavinking** [comment]
> Perhaps conceptually… but they’re used completely differently. One is a callable, typically used (in my experience) for `map`, `filter`, etc.. The other is a regular value, used for whatever you normally use values for.


Consider `stream.map` vs `stream.size`. One is a callable .... the other is a regular value ...

**Comment by gavinking** [comment]
Actually, historically, there was another reason why `object` declarations didn't have an uppercase name: it was because their types are erased by type inference, so that if you write:

```ceylon
value bool = true;
```

Then `bool` has type `Boolean`, not `True`. In the early days I was very much thinking about `Boolean` and not about bigger enums where you might want to indicate subsets using a union type.

Now we've kind of broken that a little bit by giving constructors uppercase names, but still saying that their types are erased by type inference. Nevertheless, it suggests that this would be a reasonably resolution to this train of thought:

- For `object`s like `true` and `false`, keep giving them initial-lowercase names, indicating that types should be erased during type inference.
- For `object`s where we would like to be able to denote their types, and have type inference retain them, let you given them initial-uppercase names.
- Give all constructors&mdash;including value constructors&mdash;initial-uppercase names always (but their types are always erased).

**Comment by chochos** [comment]
So `object Foo{}` will be of type `Foo`, instead of some anonymous class?

**Comment by gavinking** [comment]
@chochos yes.

```ceylon
object Foo { ... }

value foo = Foo; //foo has inferred type Foo
```

**Comment by jvasileff** [comment]
Would these be valid/make sense?
```ceylon
value t = \Itrue; // inferred type \Itrue
value foo = \iFoo; // inferred type Object & whatever
```

**Comment by gavinking** [comment]
@jvasileff Well, no, that wasn't the idea / isn't the way it works.

**Comment by gavinking** [comment]
So this morning I discussed the question of case of constructor names with @tombentley and it's interesting to reflect on this question a bit. Originally, I asked myself 

> what Ceylon 1.0 things are constructors most like?

And it seemed to me that (callable) constructors were most like _classes_:

- they have parameters,
- they have an `extends` clause,
- they can occur in an `extends` clause, 
- they can occur on the RHS of a `class` alias,
- they instantiate something when you reference them, and
- the code in the body of a constructor looks like the code in the body of a `class`, not like the code in the body of a method.

A little later, it seemed to me that value constructors were most like `object`s:

- they are a single value (no parameters)
- they can occur in `of`,
- they can occur in a value `case` of a `switch` (and not in a type `case`),
- they have an `extends` clause,
- they can't occur in an `extends` clause or on the RHS of a `class` alias, 
- a reference doesn't perform instantiation&mdash;it just returns a cached instance,
- the code in the body of a constructor looks like the code in the body of an `object`, not like the code in the body of a method.

Therefore, it seemed natural to me that:

- callable constructors have initial uppercase names, but
- value constructors have initial lowercase names.

And plus, I just found those options very aesthetically appealing for some reason. 

I certainly _considered_ giving them all lowercase names, but I very much liked being able to easily visually distinguish constructor references from static method references.

Today Tom put a pretty strong case that the above is a bit rubbish. His argument goes something like this:

> _Actually_, any rational person would think that callable constructors are most like methods, and value constructors are most like values. Indeed, they look especially like `static` methods and `static` values. Furthermore, the real difference between things with initial-uppercase names and initial-lowercase names in Ceylon 1.0 is the bleeding obvious: initial-uppercase names are for types! A constructor isn't a type.

This is rather a strong argument. And honestly I could get with it, depending upon what others think about the matter.

But let me push back against that view for a second. This afternoon, I realizes that in fact, if one is to postulate some future support for `static` (which we might introduce if we ever want to support type classes), then in fact the closest analogy is still:

- a callable constructor is a `static` member class that extends the class it belongs to, and
- a value constructor is a `static` member `object` that extends the class it belongs to.

This analogy explains why TF it is that a constructor is allowed to assign to the members of the outer class, when a `static` method would definitely not be allowed to do that. It also explains the `extends` syntax and other similarities listed above.

So to me that's a pretty clean justification for the naming conventions.

(Of course, it still doesn't resolve the question of whether `object`s and value constructors should really have uppercase names as suggested in this issue, but it at least justifies the uppercase naming of callable constructors.)

**Comment by gavinking** [comment]
FTR, the visual aesthetics issue is a little complicated:

- I much prefer `Point.Polar(0.0,0.0)` to `Point.polar(0.0,0.0)`, _especially_ if I `import` it and use it as `Polar(0.0,0.0)` vs `polar(0.0,0.0)`.
- OTOH, I prefer `Array.ofSize(10,null)` to `Array.OfSize(10,null)`.
- And I strongly prefer `new origin extends Cartesian(0.0,0.0)` to `new origin extends cartesian(0.0,0.0)`.

**Comment by luolong** [comment]
I tend to agree with Gavin's last statement. Nothing more significant to add here.

**Comment by kpdonn** [comment]
My experience with Ceylon is just from playing around with it in my spare time so I don't know if this is totally off the mark but my thoughts:

Coming from a Java background, `Point.Polar(0.0,0.0)` looks like you are instantiating a static inner class `Point.Polar`, not a `Point`. (In fact from what I understand about Ceylon, I assume you actually could be doing that?) `Point.polar(0.0,0.0)` at least looks like a static factory method which makes more sense to me but maybe that's not ideal either since it's not a factory method it's a real constructor.

The random idea I had though was why not require a `new` operator when calling these named constructors? I don't know the exact reasoning behind not requiring a `new` in Ceylon the way Java does but my guess it was probably because it seems like pointless information when the constructor has the exact same name as the class? Now that constructors don't have the exact same name as the class it seems like `new` could legitimately be valuable for readability sake. 

So I'd be proposing something like `value myPoint = new Point.polar(0.0,0.0)`. I know you have `new` already reserved so it seems at least theoretically possible. I assume you'd have to keep allowing stuff like `value myPoint = Point(0.0,0.0)` for backwards compatibility, but I imagine you could restrict the named constructors to always require the `new` since they previously haven't existed. 

That's my idea, apologies if there is something fundamentally wrong with it.

**Comment by gavinking** [comment]
@kpdonn 

> That's my idea, apologies if there is something fundamentally wrong with it.

No, nothing fundamentally wrong at all. We could do that.

But let me explain why I'm not a fan of the `new` operator:

- It "naturally" has a very high precedence, which always looks wrong for a keyword. i.e. it would have a higher precedence than `+`, `*`, etc, even though visually it looks like it has a lower precedence.
- Worse, you have a choice between allowing `new Class.constructor().method()`, where unnaturally `new` binds more tightly to `Class.constructor()` than `.method()` does, or requiring people to write `(new Class.constructor()).method()`.
- To my mind, it implies that constructors are more different to other functions than they actually are.

**Comment by kpdonn** [comment]
Fair enough, but in that case I'd argue pretty strongly that the lowercase version is much clearer than the uppercase. The reason is basically your final bullet point:

>To my mind, it implies that constructors are more different to other functions than they actually are.

I think that same statement would also apply to using uppercase naming for the constructor. It makes them look far less like functions and far more like their own types.

**Comment by gavinking** [comment]
After a long discussion we finally settled on lowercase named from constructors. I _still_ don't find it as visually appealing, but it seems conceptually cleaner.
