### ISSUE TITLE
Backend-specific source files

### ISSUE THREAD

**Issue by FroMage** [ceylon/ceylon-spec#500]
We need to figure out how to have certain files only compiled for certain backends. It could be as simple as saying `.java` files for the JVM backend and `.js` files for the JS backend, but we may also want different Ceylon source files for different backends, as glue or something.

**Comment by gavinking** [comment]
@quintesse has been working on this.

**Comment by quintesse** [comment]
Closing this, what is implemented right now:

```ceylon
"You'd put your documentation here"
native
shared void test();

native("jvm")
shared void test() { print("A test for the JVM"; }

native("js")
shared void test() { print("A test for JS"; }

shared void run() { test(); }
```

for toplevel methods (as shown), attributes and classes.

The signatures of the declarations with the same name have to be identical.
The declaration that is simply marked `native` is called the "abstraction" while the ones that have a native annotation with an argument are called "implementations".
The only allowed arguments to the native annotation are: `jvm` and `js`.
A declaration that is `shared` *must* have an abstraction, otherwise it's optional (but the implementations still need to have identical signatures).
Method and attribute abstractions and members of class abstractions can leave out their implementation (if you specify them they will be ignored by the compilers).

There's no support for imports right now, this is ongoing for #499.

**Comment by quintesse** [comment]
Btw, this doesn't implement exactly what was proposed in the original text of this issue. But for now this new implementation supersedes that idea.

@gavinking when you fix the error messages please give me a heads-up so I can fix the tests.

**Comment by gavinking** [comment]
Fantastic, congratulations!

**Comment by FroMage** [comment]
Great! So what does this mean for Java or JS declarations then? Can we still have them?

**Comment by quintesse** [comment]
What are you referring to exactly @FroMage ?

**Comment by FroMage** [comment]
Suppose I need to write a Java or JS class/function? In a `.java` or `.js` file?

**Comment by gavinking** [comment]
@FroMage In principle, yes, because that's the case of just a `native` header and no implementation. In practice I'm not sure if the JVM compiler can handle this anywhere outside of the language module. (The JS compiler _does_ support it, I believe.

**Comment by quintesse** [comment]
Yes, you can do it like this for example (directly from my test module):

```ceylon
shared void run() {
    testNative();
}

native("jvm") void testNative() {
    myprintJvm(NativeCode().test());
}

native("js") void testNative() {
    dynamic {
        myprintJs(nativeCode());
    }
}
```

and then have:

```java
public class NativeCode {
    public String test() {
        return "This is a native Java class";
    }
}
```

and:

```js
function nativeCode() {
    return "This is a native JavaScript function";
}
```

(you'll need to have the latest code though, I just fixed a bug related to this)

**Comment by FroMage** [comment]
Oh, so you can. How does the IDE behave in this case? I expect it not to see `nativeCode` from js since the JS model loader is not plugged in the IDE, but will it see the `NativeCode` class in Ceylon code? Will it not allow you to call it even outside native methods?

**Comment by quintesse** [comment]
The IDE hasn't changed behaviour for what was already there.
So you can just call `NativeCode` outside of native methods, you'll just not be able to enable the JS backend because you'll get errors.
The same with using `dynamic` and trying to enable the JVM backend.
But you *can* enable both backends and then put those calls in native methods and everything should work.
I say "should" because right now the IDE does have a problem still with JVM code. I'm looking into that.

**Comment by quintesse** [comment]
Ok, the IDE problem is now fixed.
