### ISSUE TITLE
serialization

### ISSUE THREAD

**Issue by gavinking** [ceylon/ceylon-spec#704]
We need to define:

1. a set of rules that determine if a class is serializable (restrictions on it's attribute types, annotations, etc), and
2. an API, as part of the metamodel, which supports `Serializer`s and serialization.

I'm thinking something along the lines of this:

A class is serializable iff:

1. it is annotated `serializable`,
2. it has no forward-declared methods or getters,
3. all its reference attributes are either `serializable` or `shared`, and
4. all its reference attributes are of `serializable` type.

All superclasses and all subclasses of a `serializable` class must also be serializable, except for `Object` and `Anything`.

But I'm sure I'm missing some details.

**Comment by tombentley** [comment]
@gavinking checkout the serialization branch of ceylon.language. There's also https://github.com/tombentley/jsonsl/ which you may, or may not be interested in. Note that @chochos hasn't yet had a chance to update the JS language module, so it's JVM only right now.

**Comment by quintesse** [comment]
I like how easy the use of the library is! Nice work.

**Comment by EricSL** [comment]
If jsonsl is any indication of what this is intended to support, this proposal seems to be going in the wrong direction. 

There are a few key things serialization libraries need to get right:
1. Cross version compatibility -- think about things like what happens when the code changes; can a field change from type T? to Sequence<T>, how do you specify default values in case it's missing.
2. Cross language compatibility -- a JSON parser needs to work with JSON the way others are using JSON. Representing things in a Ceylon-specific way, by for example including the names of the Ceylon types, is a bad pattern here. Likewise, serialized names that aren't valid Ceylon field names need to be supported, and case insensitive field names may be desirable.)
3. Security -- Assume the serialized version could be maliciously created; don't instantiate any objects that aren't expected.

(Maybe you're shooting for something more along the lines of Python's pickling, but if so it will be of much more limited use. If not, these concerns need to override completeness concerns.)

What's not so important is serializing graphs. There isn't one conventional way to do this, so you'll have trouble with compatibility with the various ways people encode them now. Instead expect that developers will translate their graphs to/from a serializable acyclic intermediate form that just represents the data, and the serialization library will make it easy to serialize that.

What's not so important is supporting inheritance. Due to security concerns, if the schema says you are deserializing type T, it is not okay to deserialize a subclass of T. It can be okay if the schema explicitly lists the supported subtypes, but if so you need a cross-language compatible way of specifying what the type is. For example, annotations might say that field foo will contain type T if the JSON contains a field "foo_t", or a type U if the JSON contains a field "foo_u". Something equivalent to the oneof feature in protobuf could be an alternative to inheritance: https://developers.google.com/protocol-buffers/docs/proto#oneof  Inheritance seems natural in XML but like I said you want to be explicit about what classes you are expecting to deserialize.

It may be helpful to distinguish between root-serializable and field-serializable. I don't think the standard collections should support serialization directly. However, it should obviously be supported to have serializable classes with fields of type Sequence<T> where T is also serializable.

It may be helpful to start from another language's API just because then there's a decent chance you'll interoperate with that language. C# has an annotation based serialization API, and it was designed around XML, but it works quite well for JSON: https://msdn.microsoft.com/en-us/library/bb410770%28v=vs.110%29.aspx

**Comment by gavinking** [comment]
> If jsonsl is any indication of what this is intended to support, this proposal seems to be going in the wrong direction. .... There are a few key things serialization libraries need to get right:

I don't understand this comment _at all_. The current API externalizes the listed concerns (among others) to the serialization library itself, and quite deliberately avoids addressing this kind of concern in the language module! 

> Maybe you're shooting for something more along the lines of Python's pickling, but if so it will be of much more limited use.

Well that is what _jasonsl_ is, but it is not the only thing that the language module serialization API is capable of supporting.

I don't think you've understood the architecture of this.

> It may be helpful to start from another language's API

Yew. All other languages handle serialization _really badly_, in my experience.

> C# has an annotation based serialization API

Sure, and the current API can certainly support serialization libraries which are annotation driven. Indeed, that is a central goal. But we certainly don't want to bloat out the _language module_ with annotations for controlling serialization!

**Comment by gavinking** [comment]
Note that, indications at present are that the current API is too general-purposed, and perhaps won't be capable of supporting reasonable performance. So we might need to scale back our vision here, and provide something much less general-purpose.

**Comment by sirinath** [comment]
One thing I can request is make it flexible as to make this at compile time resolution of runtime resolution. You can look at the AST of the object to be serialised and map into the serialisation format at compile time and in runtime you will need some form of fast reflection.

**Comment by gavinking** [comment]
I'm closing this because, in principle, it's done.

We can open new issues for any additional tasks, which probably don't anyway affect ceylon-spec.
